# Generated by Django 3.1.5 on 2021-06-02 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('patientlevel', models.CharField(choices=[('covid_bed', 'covid-19 Beds'), ('oxygen_bed', 'covid-19 Oxygen Beds'), ('icu_bed', 'covid-19 ICU Beds'), ('icu_ventilator_bed', 'covid-19 ICU Beds with Ventilators')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
